// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-TrurgDHph2XuJ_C9aaScn7kgsSEl6E4',
    appId: '1:788479091998:web:d10f1ad72e81270b11d50f',
    messagingSenderId: '788479091998',
    projectId: 'cantique-liturgique-d1b5b',
    authDomain: 'cantique-liturgique-d1b5b.firebaseapp.com',
    storageBucket: 'cantique-liturgique-d1b5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVMFLLFwvo3e7xHkjJnTkOUuzdcKYYpI',
    appId: '1:788479091998:android:63ff5d1a7b4a14cb11d50f',
    messagingSenderId: '788479091998',
    projectId: 'cantique-liturgique-d1b5b',
    storageBucket: 'cantique-liturgique-d1b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqr4TgKvoOoiVtcY9BpdhgQF0pT2YuBQE',
    appId: '1:788479091998:ios:e14dab3dffaadfaa11d50f',
    messagingSenderId: '788479091998',
    projectId: 'cantique-liturgique-d1b5b',
    storageBucket: 'cantique-liturgique-d1b5b.firebasestorage.app',
    iosBundleId: 'com.example.cantiqueLiturgique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqr4TgKvoOoiVtcY9BpdhgQF0pT2YuBQE',
    appId: '1:788479091998:ios:e14dab3dffaadfaa11d50f',
    messagingSenderId: '788479091998',
    projectId: 'cantique-liturgique-d1b5b',
    storageBucket: 'cantique-liturgique-d1b5b.firebasestorage.app',
    iosBundleId: 'com.example.cantiqueLiturgique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-TrurgDHph2XuJ_C9aaScn7kgsSEl6E4',
    appId: '1:788479091998:web:a47107de62a0b89811d50f',
    messagingSenderId: '788479091998',
    projectId: 'cantique-liturgique-d1b5b',
    authDomain: 'cantique-liturgique-d1b5b.firebaseapp.com',
    storageBucket: 'cantique-liturgique-d1b5b.firebasestorage.app',
  );
}
